import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "User",
  description: "Generated by create next app",
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <>
   hello
    {children}
   </>
  );
}
